/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardStaffRouteImport } from './routes/dashboard.staff'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardClientRouteImport } from './routes/dashboard/client'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardStaffIndexRouteImport } from './routes/dashboard.staff.index'
import { Route as DashboardClientIndexRouteImport } from './routes/dashboard/client.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardStaffTasksRouteImport } from './routes/dashboard.staff.tasks'
import { Route as DashboardStaffProfileRouteImport } from './routes/dashboard.staff.profile'
import { Route as DashboardStaffMessagesRouteImport } from './routes/dashboard.staff.messages'
import { Route as DashboardStaffLeadsRouteImport } from './routes/dashboard.staff.leads'
import { Route as DashboardStaffDocumentsRouteImport } from './routes/dashboard.staff.documents'
import { Route as DashboardStaffClientsRouteImport } from './routes/dashboard.staff.clients'
import { Route as DashboardStaffAppointmentsRouteImport } from './routes/dashboard.staff.appointments'
import { Route as DashboardStaffApplicationsRouteImport } from './routes/dashboard.staff.applications'
import { Route as DashboardClientProfileRouteImport } from './routes/dashboard/client.profile'
import { Route as DashboardClientPaymentsRouteImport } from './routes/dashboard/client.payments'
import { Route as DashboardClientMessagesRouteImport } from './routes/dashboard/client.messages'
import { Route as DashboardClientDocumentsRouteImport } from './routes/dashboard/client.documents'
import { Route as DashboardClientAppointmentsRouteImport } from './routes/dashboard/client.appointments'
import { Route as DashboardClientApplicationRouteImport } from './routes/dashboard/client.application'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminProfileRouteImport } from './routes/dashboard.admin.profile'
import { Route as DashboardAdminLeadsRouteImport } from './routes/dashboard.admin.leads'
import { Route as DashboardAdminContentRouteImport } from './routes/dashboard.admin.content'
import { Route as DashboardAdminClientsRouteImport } from './routes/dashboard.admin.clients'
import { Route as DashboardAdminApplicationsRouteImport } from './routes/dashboard.admin.applications'
import { Route as DashboardStaffLeadsLeadIdRouteImport } from './routes/dashboard.staff.leads.$leadId'
import { Route as DashboardStaffClientsClientIdRouteImport } from './routes/dashboard.staff.clients.$clientId'
import { Route as DashboardStaffApplicationsApplicationIdRouteImport } from './routes/dashboard.staff.applications.$applicationId'
import { Route as DashboardAdminLeadsLeadIdRouteImport } from './routes/dashboard.admin.leads.$leadId'
import { Route as DashboardAdminClientsClientIdRouteImport } from './routes/dashboard.admin.clients.$clientId'
import { Route as DashboardAdminApplicationsApplicationIdRouteImport } from './routes/dashboard.admin.applications.$applicationId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientRoute = DashboardClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardClientIndexRoute = DashboardClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardStaffTasksRoute = DashboardStaffTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardStaffProfileRoute = DashboardStaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardStaffMessagesRoute = DashboardStaffMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardStaffLeadsRoute = DashboardStaffLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardStaffDocumentsRoute = DashboardStaffDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardStaffClientsRoute = DashboardStaffClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardStaffRoute,
} as any)
const DashboardStaffAppointmentsRoute =
  DashboardStaffAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DashboardStaffRoute,
  } as any)
const DashboardStaffApplicationsRoute =
  DashboardStaffApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => DashboardStaffRoute,
  } as any)
const DashboardClientProfileRoute = DashboardClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardClientPaymentsRoute = DashboardClientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardClientMessagesRoute = DashboardClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardClientRoute,
} as any)
const DashboardClientDocumentsRoute =
  DashboardClientDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DashboardClientRoute,
  } as any)
const DashboardClientAppointmentsRoute =
  DashboardClientAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => DashboardClientRoute,
  } as any)
const DashboardClientApplicationRoute =
  DashboardClientApplicationRouteImport.update({
    id: '/application',
    path: '/application',
    getParentRoute: () => DashboardClientRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminProfileRoute = DashboardAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminLeadsRoute = DashboardAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminContentRoute = DashboardAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminClientsRoute = DashboardAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminApplicationsRoute =
  DashboardAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardStaffLeadsLeadIdRoute =
  DashboardStaffLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => DashboardStaffLeadsRoute,
  } as any)
const DashboardStaffClientsClientIdRoute =
  DashboardStaffClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => DashboardStaffClientsRoute,
  } as any)
const DashboardStaffApplicationsApplicationIdRoute =
  DashboardStaffApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => DashboardStaffApplicationsRoute,
  } as any)
const DashboardAdminLeadsLeadIdRoute =
  DashboardAdminLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => DashboardAdminLeadsRoute,
  } as any)
const DashboardAdminClientsClientIdRoute =
  DashboardAdminClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => DashboardAdminClientsRoute,
  } as any)
const DashboardAdminApplicationsApplicationIdRoute =
  DashboardAdminApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => DashboardAdminApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client-portal': typeof ClientPortalRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/client': typeof DashboardClientRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/staff': typeof DashboardStaffRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/applications': typeof DashboardAdminApplicationsRouteWithChildren
  '/dashboard/admin/clients': typeof DashboardAdminClientsRouteWithChildren
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRouteWithChildren
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/client/application': typeof DashboardClientApplicationRoute
  '/dashboard/client/appointments': typeof DashboardClientAppointmentsRoute
  '/dashboard/client/documents': typeof DashboardClientDocumentsRoute
  '/dashboard/client/messages': typeof DashboardClientMessagesRoute
  '/dashboard/client/payments': typeof DashboardClientPaymentsRoute
  '/dashboard/client/profile': typeof DashboardClientProfileRoute
  '/dashboard/staff/applications': typeof DashboardStaffApplicationsRouteWithChildren
  '/dashboard/staff/appointments': typeof DashboardStaffAppointmentsRoute
  '/dashboard/staff/clients': typeof DashboardStaffClientsRouteWithChildren
  '/dashboard/staff/documents': typeof DashboardStaffDocumentsRoute
  '/dashboard/staff/leads': typeof DashboardStaffLeadsRouteWithChildren
  '/dashboard/staff/messages': typeof DashboardStaffMessagesRoute
  '/dashboard/staff/profile': typeof DashboardStaffProfileRoute
  '/dashboard/staff/tasks': typeof DashboardStaffTasksRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/client/': typeof DashboardClientIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/admin/applications/$applicationId': typeof DashboardAdminApplicationsApplicationIdRoute
  '/dashboard/admin/clients/$clientId': typeof DashboardAdminClientsClientIdRoute
  '/dashboard/admin/leads/$leadId': typeof DashboardAdminLeadsLeadIdRoute
  '/dashboard/staff/applications/$applicationId': typeof DashboardStaffApplicationsApplicationIdRoute
  '/dashboard/staff/clients/$clientId': typeof DashboardStaffClientsClientIdRoute
  '/dashboard/staff/leads/$leadId': typeof DashboardStaffLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client-portal': typeof ClientPortalRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/applications': typeof DashboardAdminApplicationsRouteWithChildren
  '/dashboard/admin/clients': typeof DashboardAdminClientsRouteWithChildren
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRouteWithChildren
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/client/application': typeof DashboardClientApplicationRoute
  '/dashboard/client/appointments': typeof DashboardClientAppointmentsRoute
  '/dashboard/client/documents': typeof DashboardClientDocumentsRoute
  '/dashboard/client/messages': typeof DashboardClientMessagesRoute
  '/dashboard/client/payments': typeof DashboardClientPaymentsRoute
  '/dashboard/client/profile': typeof DashboardClientProfileRoute
  '/dashboard/staff/applications': typeof DashboardStaffApplicationsRouteWithChildren
  '/dashboard/staff/appointments': typeof DashboardStaffAppointmentsRoute
  '/dashboard/staff/clients': typeof DashboardStaffClientsRouteWithChildren
  '/dashboard/staff/documents': typeof DashboardStaffDocumentsRoute
  '/dashboard/staff/leads': typeof DashboardStaffLeadsRouteWithChildren
  '/dashboard/staff/messages': typeof DashboardStaffMessagesRoute
  '/dashboard/staff/profile': typeof DashboardStaffProfileRoute
  '/dashboard/staff/tasks': typeof DashboardStaffTasksRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/client': typeof DashboardClientIndexRoute
  '/dashboard/staff': typeof DashboardStaffIndexRoute
  '/dashboard/admin/applications/$applicationId': typeof DashboardAdminApplicationsApplicationIdRoute
  '/dashboard/admin/clients/$clientId': typeof DashboardAdminClientsClientIdRoute
  '/dashboard/admin/leads/$leadId': typeof DashboardAdminLeadsLeadIdRoute
  '/dashboard/staff/applications/$applicationId': typeof DashboardStaffApplicationsApplicationIdRoute
  '/dashboard/staff/clients/$clientId': typeof DashboardStaffClientsClientIdRoute
  '/dashboard/staff/leads/$leadId': typeof DashboardStaffLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client-portal': typeof ClientPortalRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/client': typeof DashboardClientRouteWithChildren
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/staff': typeof DashboardStaffRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/applications': typeof DashboardAdminApplicationsRouteWithChildren
  '/dashboard/admin/clients': typeof DashboardAdminClientsRouteWithChildren
  '/dashboard/admin/content': typeof DashboardAdminContentRoute
  '/dashboard/admin/leads': typeof DashboardAdminLeadsRouteWithChildren
  '/dashboard/admin/profile': typeof DashboardAdminProfileRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/client/application': typeof DashboardClientApplicationRoute
  '/dashboard/client/appointments': typeof DashboardClientAppointmentsRoute
  '/dashboard/client/documents': typeof DashboardClientDocumentsRoute
  '/dashboard/client/messages': typeof DashboardClientMessagesRoute
  '/dashboard/client/payments': typeof DashboardClientPaymentsRoute
  '/dashboard/client/profile': typeof DashboardClientProfileRoute
  '/dashboard/staff/applications': typeof DashboardStaffApplicationsRouteWithChildren
  '/dashboard/staff/appointments': typeof DashboardStaffAppointmentsRoute
  '/dashboard/staff/clients': typeof DashboardStaffClientsRouteWithChildren
  '/dashboard/staff/documents': typeof DashboardStaffDocumentsRoute
  '/dashboard/staff/leads': typeof DashboardStaffLeadsRouteWithChildren
  '/dashboard/staff/messages': typeof DashboardStaffMessagesRoute
  '/dashboard/staff/profile': typeof DashboardStaffProfileRoute
  '/dashboard/staff/tasks': typeof DashboardStaffTasksRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/client/': typeof DashboardClientIndexRoute
  '/dashboard/staff/': typeof DashboardStaffIndexRoute
  '/dashboard/admin/applications/$applicationId': typeof DashboardAdminApplicationsApplicationIdRoute
  '/dashboard/admin/clients/$clientId': typeof DashboardAdminClientsClientIdRoute
  '/dashboard/admin/leads/$leadId': typeof DashboardAdminLeadsLeadIdRoute
  '/dashboard/staff/applications/$applicationId': typeof DashboardStaffApplicationsApplicationIdRoute
  '/dashboard/staff/clients/$clientId': typeof DashboardStaffClientsClientIdRoute
  '/dashboard/staff/leads/$leadId': typeof DashboardStaffLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/client-portal'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/clients'
    | '/dashboard/content'
    | '/dashboard/profile'
    | '/dashboard/staff'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/admin/applications'
    | '/dashboard/admin/clients'
    | '/dashboard/admin/content'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/users'
    | '/dashboard/client/application'
    | '/dashboard/client/appointments'
    | '/dashboard/client/documents'
    | '/dashboard/client/messages'
    | '/dashboard/client/payments'
    | '/dashboard/client/profile'
    | '/dashboard/staff/applications'
    | '/dashboard/staff/appointments'
    | '/dashboard/staff/clients'
    | '/dashboard/staff/documents'
    | '/dashboard/staff/leads'
    | '/dashboard/staff/messages'
    | '/dashboard/staff/profile'
    | '/dashboard/staff/tasks'
    | '/dashboard/admin/'
    | '/dashboard/client/'
    | '/dashboard/staff/'
    | '/dashboard/admin/applications/$applicationId'
    | '/dashboard/admin/clients/$clientId'
    | '/dashboard/admin/leads/$leadId'
    | '/dashboard/staff/applications/$applicationId'
    | '/dashboard/staff/clients/$clientId'
    | '/dashboard/staff/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/client-portal'
    | '/dashboard/clients'
    | '/dashboard/content'
    | '/dashboard/profile'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/admin/applications'
    | '/dashboard/admin/clients'
    | '/dashboard/admin/content'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/users'
    | '/dashboard/client/application'
    | '/dashboard/client/appointments'
    | '/dashboard/client/documents'
    | '/dashboard/client/messages'
    | '/dashboard/client/payments'
    | '/dashboard/client/profile'
    | '/dashboard/staff/applications'
    | '/dashboard/staff/appointments'
    | '/dashboard/staff/clients'
    | '/dashboard/staff/documents'
    | '/dashboard/staff/leads'
    | '/dashboard/staff/messages'
    | '/dashboard/staff/profile'
    | '/dashboard/staff/tasks'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/staff'
    | '/dashboard/admin/applications/$applicationId'
    | '/dashboard/admin/clients/$clientId'
    | '/dashboard/admin/leads/$leadId'
    | '/dashboard/staff/applications/$applicationId'
    | '/dashboard/staff/clients/$clientId'
    | '/dashboard/staff/leads/$leadId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/client-portal'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/clients'
    | '/dashboard/content'
    | '/dashboard/profile'
    | '/dashboard/staff'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/admin/applications'
    | '/dashboard/admin/clients'
    | '/dashboard/admin/content'
    | '/dashboard/admin/leads'
    | '/dashboard/admin/profile'
    | '/dashboard/admin/users'
    | '/dashboard/client/application'
    | '/dashboard/client/appointments'
    | '/dashboard/client/documents'
    | '/dashboard/client/messages'
    | '/dashboard/client/payments'
    | '/dashboard/client/profile'
    | '/dashboard/staff/applications'
    | '/dashboard/staff/appointments'
    | '/dashboard/staff/clients'
    | '/dashboard/staff/documents'
    | '/dashboard/staff/leads'
    | '/dashboard/staff/messages'
    | '/dashboard/staff/profile'
    | '/dashboard/staff/tasks'
    | '/dashboard/admin/'
    | '/dashboard/client/'
    | '/dashboard/staff/'
    | '/dashboard/admin/applications/$applicationId'
    | '/dashboard/admin/clients/$clientId'
    | '/dashboard/admin/leads/$leadId'
    | '/dashboard/staff/applications/$applicationId'
    | '/dashboard/staff/clients/$clientId'
    | '/dashboard/staff/leads/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClientPortalRoute: typeof ClientPortalRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client': {
      id: '/dashboard/client'
      path: '/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof DashboardClientRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff/': {
      id: '/dashboard/staff/'
      path: '/'
      fullPath: '/dashboard/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/client/': {
      id: '/dashboard/client/'
      path: '/'
      fullPath: '/dashboard/client/'
      preLoaderRoute: typeof DashboardClientIndexRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/staff/tasks': {
      id: '/dashboard/staff/tasks'
      path: '/tasks'
      fullPath: '/dashboard/staff/tasks'
      preLoaderRoute: typeof DashboardStaffTasksRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/profile': {
      id: '/dashboard/staff/profile'
      path: '/profile'
      fullPath: '/dashboard/staff/profile'
      preLoaderRoute: typeof DashboardStaffProfileRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/messages': {
      id: '/dashboard/staff/messages'
      path: '/messages'
      fullPath: '/dashboard/staff/messages'
      preLoaderRoute: typeof DashboardStaffMessagesRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/leads': {
      id: '/dashboard/staff/leads'
      path: '/leads'
      fullPath: '/dashboard/staff/leads'
      preLoaderRoute: typeof DashboardStaffLeadsRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/documents': {
      id: '/dashboard/staff/documents'
      path: '/documents'
      fullPath: '/dashboard/staff/documents'
      preLoaderRoute: typeof DashboardStaffDocumentsRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/clients': {
      id: '/dashboard/staff/clients'
      path: '/clients'
      fullPath: '/dashboard/staff/clients'
      preLoaderRoute: typeof DashboardStaffClientsRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/appointments': {
      id: '/dashboard/staff/appointments'
      path: '/appointments'
      fullPath: '/dashboard/staff/appointments'
      preLoaderRoute: typeof DashboardStaffAppointmentsRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/staff/applications': {
      id: '/dashboard/staff/applications'
      path: '/applications'
      fullPath: '/dashboard/staff/applications'
      preLoaderRoute: typeof DashboardStaffApplicationsRouteImport
      parentRoute: typeof DashboardStaffRoute
    }
    '/dashboard/client/profile': {
      id: '/dashboard/client/profile'
      path: '/profile'
      fullPath: '/dashboard/client/profile'
      preLoaderRoute: typeof DashboardClientProfileRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/payments': {
      id: '/dashboard/client/payments'
      path: '/payments'
      fullPath: '/dashboard/client/payments'
      preLoaderRoute: typeof DashboardClientPaymentsRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/messages': {
      id: '/dashboard/client/messages'
      path: '/messages'
      fullPath: '/dashboard/client/messages'
      preLoaderRoute: typeof DashboardClientMessagesRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/documents': {
      id: '/dashboard/client/documents'
      path: '/documents'
      fullPath: '/dashboard/client/documents'
      preLoaderRoute: typeof DashboardClientDocumentsRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/appointments': {
      id: '/dashboard/client/appointments'
      path: '/appointments'
      fullPath: '/dashboard/client/appointments'
      preLoaderRoute: typeof DashboardClientAppointmentsRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/client/application': {
      id: '/dashboard/client/application'
      path: '/application'
      fullPath: '/dashboard/client/application'
      preLoaderRoute: typeof DashboardClientApplicationRouteImport
      parentRoute: typeof DashboardClientRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/profile': {
      id: '/dashboard/admin/profile'
      path: '/profile'
      fullPath: '/dashboard/admin/profile'
      preLoaderRoute: typeof DashboardAdminProfileRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/leads': {
      id: '/dashboard/admin/leads'
      path: '/leads'
      fullPath: '/dashboard/admin/leads'
      preLoaderRoute: typeof DashboardAdminLeadsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/content': {
      id: '/dashboard/admin/content'
      path: '/content'
      fullPath: '/dashboard/admin/content'
      preLoaderRoute: typeof DashboardAdminContentRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/clients': {
      id: '/dashboard/admin/clients'
      path: '/clients'
      fullPath: '/dashboard/admin/clients'
      preLoaderRoute: typeof DashboardAdminClientsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/applications': {
      id: '/dashboard/admin/applications'
      path: '/applications'
      fullPath: '/dashboard/admin/applications'
      preLoaderRoute: typeof DashboardAdminApplicationsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/staff/leads/$leadId': {
      id: '/dashboard/staff/leads/$leadId'
      path: '/$leadId'
      fullPath: '/dashboard/staff/leads/$leadId'
      preLoaderRoute: typeof DashboardStaffLeadsLeadIdRouteImport
      parentRoute: typeof DashboardStaffLeadsRoute
    }
    '/dashboard/staff/clients/$clientId': {
      id: '/dashboard/staff/clients/$clientId'
      path: '/$clientId'
      fullPath: '/dashboard/staff/clients/$clientId'
      preLoaderRoute: typeof DashboardStaffClientsClientIdRouteImport
      parentRoute: typeof DashboardStaffClientsRoute
    }
    '/dashboard/staff/applications/$applicationId': {
      id: '/dashboard/staff/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/dashboard/staff/applications/$applicationId'
      preLoaderRoute: typeof DashboardStaffApplicationsApplicationIdRouteImport
      parentRoute: typeof DashboardStaffApplicationsRoute
    }
    '/dashboard/admin/leads/$leadId': {
      id: '/dashboard/admin/leads/$leadId'
      path: '/$leadId'
      fullPath: '/dashboard/admin/leads/$leadId'
      preLoaderRoute: typeof DashboardAdminLeadsLeadIdRouteImport
      parentRoute: typeof DashboardAdminLeadsRoute
    }
    '/dashboard/admin/clients/$clientId': {
      id: '/dashboard/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/dashboard/admin/clients/$clientId'
      preLoaderRoute: typeof DashboardAdminClientsClientIdRouteImport
      parentRoute: typeof DashboardAdminClientsRoute
    }
    '/dashboard/admin/applications/$applicationId': {
      id: '/dashboard/admin/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/dashboard/admin/applications/$applicationId'
      preLoaderRoute: typeof DashboardAdminApplicationsApplicationIdRouteImport
      parentRoute: typeof DashboardAdminApplicationsRoute
    }
  }
}

interface DashboardAdminApplicationsRouteChildren {
  DashboardAdminApplicationsApplicationIdRoute: typeof DashboardAdminApplicationsApplicationIdRoute
}

const DashboardAdminApplicationsRouteChildren: DashboardAdminApplicationsRouteChildren =
  {
    DashboardAdminApplicationsApplicationIdRoute:
      DashboardAdminApplicationsApplicationIdRoute,
  }

const DashboardAdminApplicationsRouteWithChildren =
  DashboardAdminApplicationsRoute._addFileChildren(
    DashboardAdminApplicationsRouteChildren,
  )

interface DashboardAdminClientsRouteChildren {
  DashboardAdminClientsClientIdRoute: typeof DashboardAdminClientsClientIdRoute
}

const DashboardAdminClientsRouteChildren: DashboardAdminClientsRouteChildren = {
  DashboardAdminClientsClientIdRoute: DashboardAdminClientsClientIdRoute,
}

const DashboardAdminClientsRouteWithChildren =
  DashboardAdminClientsRoute._addFileChildren(
    DashboardAdminClientsRouteChildren,
  )

interface DashboardAdminLeadsRouteChildren {
  DashboardAdminLeadsLeadIdRoute: typeof DashboardAdminLeadsLeadIdRoute
}

const DashboardAdminLeadsRouteChildren: DashboardAdminLeadsRouteChildren = {
  DashboardAdminLeadsLeadIdRoute: DashboardAdminLeadsLeadIdRoute,
}

const DashboardAdminLeadsRouteWithChildren =
  DashboardAdminLeadsRoute._addFileChildren(DashboardAdminLeadsRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminApplicationsRoute: typeof DashboardAdminApplicationsRouteWithChildren
  DashboardAdminClientsRoute: typeof DashboardAdminClientsRouteWithChildren
  DashboardAdminContentRoute: typeof DashboardAdminContentRoute
  DashboardAdminLeadsRoute: typeof DashboardAdminLeadsRouteWithChildren
  DashboardAdminProfileRoute: typeof DashboardAdminProfileRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminApplicationsRoute: DashboardAdminApplicationsRouteWithChildren,
  DashboardAdminClientsRoute: DashboardAdminClientsRouteWithChildren,
  DashboardAdminContentRoute: DashboardAdminContentRoute,
  DashboardAdminLeadsRoute: DashboardAdminLeadsRouteWithChildren,
  DashboardAdminProfileRoute: DashboardAdminProfileRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardClientRouteChildren {
  DashboardClientApplicationRoute: typeof DashboardClientApplicationRoute
  DashboardClientAppointmentsRoute: typeof DashboardClientAppointmentsRoute
  DashboardClientDocumentsRoute: typeof DashboardClientDocumentsRoute
  DashboardClientMessagesRoute: typeof DashboardClientMessagesRoute
  DashboardClientPaymentsRoute: typeof DashboardClientPaymentsRoute
  DashboardClientProfileRoute: typeof DashboardClientProfileRoute
  DashboardClientIndexRoute: typeof DashboardClientIndexRoute
}

const DashboardClientRouteChildren: DashboardClientRouteChildren = {
  DashboardClientApplicationRoute: DashboardClientApplicationRoute,
  DashboardClientAppointmentsRoute: DashboardClientAppointmentsRoute,
  DashboardClientDocumentsRoute: DashboardClientDocumentsRoute,
  DashboardClientMessagesRoute: DashboardClientMessagesRoute,
  DashboardClientPaymentsRoute: DashboardClientPaymentsRoute,
  DashboardClientProfileRoute: DashboardClientProfileRoute,
  DashboardClientIndexRoute: DashboardClientIndexRoute,
}

const DashboardClientRouteWithChildren = DashboardClientRoute._addFileChildren(
  DashboardClientRouteChildren,
)

interface DashboardStaffApplicationsRouteChildren {
  DashboardStaffApplicationsApplicationIdRoute: typeof DashboardStaffApplicationsApplicationIdRoute
}

const DashboardStaffApplicationsRouteChildren: DashboardStaffApplicationsRouteChildren =
  {
    DashboardStaffApplicationsApplicationIdRoute:
      DashboardStaffApplicationsApplicationIdRoute,
  }

const DashboardStaffApplicationsRouteWithChildren =
  DashboardStaffApplicationsRoute._addFileChildren(
    DashboardStaffApplicationsRouteChildren,
  )

interface DashboardStaffClientsRouteChildren {
  DashboardStaffClientsClientIdRoute: typeof DashboardStaffClientsClientIdRoute
}

const DashboardStaffClientsRouteChildren: DashboardStaffClientsRouteChildren = {
  DashboardStaffClientsClientIdRoute: DashboardStaffClientsClientIdRoute,
}

const DashboardStaffClientsRouteWithChildren =
  DashboardStaffClientsRoute._addFileChildren(
    DashboardStaffClientsRouteChildren,
  )

interface DashboardStaffLeadsRouteChildren {
  DashboardStaffLeadsLeadIdRoute: typeof DashboardStaffLeadsLeadIdRoute
}

const DashboardStaffLeadsRouteChildren: DashboardStaffLeadsRouteChildren = {
  DashboardStaffLeadsLeadIdRoute: DashboardStaffLeadsLeadIdRoute,
}

const DashboardStaffLeadsRouteWithChildren =
  DashboardStaffLeadsRoute._addFileChildren(DashboardStaffLeadsRouteChildren)

interface DashboardStaffRouteChildren {
  DashboardStaffApplicationsRoute: typeof DashboardStaffApplicationsRouteWithChildren
  DashboardStaffAppointmentsRoute: typeof DashboardStaffAppointmentsRoute
  DashboardStaffClientsRoute: typeof DashboardStaffClientsRouteWithChildren
  DashboardStaffDocumentsRoute: typeof DashboardStaffDocumentsRoute
  DashboardStaffLeadsRoute: typeof DashboardStaffLeadsRouteWithChildren
  DashboardStaffMessagesRoute: typeof DashboardStaffMessagesRoute
  DashboardStaffProfileRoute: typeof DashboardStaffProfileRoute
  DashboardStaffTasksRoute: typeof DashboardStaffTasksRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
}

const DashboardStaffRouteChildren: DashboardStaffRouteChildren = {
  DashboardStaffApplicationsRoute: DashboardStaffApplicationsRouteWithChildren,
  DashboardStaffAppointmentsRoute: DashboardStaffAppointmentsRoute,
  DashboardStaffClientsRoute: DashboardStaffClientsRouteWithChildren,
  DashboardStaffDocumentsRoute: DashboardStaffDocumentsRoute,
  DashboardStaffLeadsRoute: DashboardStaffLeadsRouteWithChildren,
  DashboardStaffMessagesRoute: DashboardStaffMessagesRoute,
  DashboardStaffProfileRoute: DashboardStaffProfileRoute,
  DashboardStaffTasksRoute: DashboardStaffTasksRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
}

const DashboardStaffRouteWithChildren = DashboardStaffRoute._addFileChildren(
  DashboardStaffRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardClientRoute: typeof DashboardClientRouteWithChildren
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStaffRoute: typeof DashboardStaffRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardClientRoute: DashboardClientRouteWithChildren,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStaffRoute: DashboardStaffRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClientPortalRoute: ClientPortalRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
